spring.application.name=url-shortner-sb
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortnerdb
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=84e48acf02d84cee
jwt.expiration=172800000

